name: Deploy Bible Quest

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'   # every six hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy script
        run: |
          pip install requests
          python deploy_only.py
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
